fix(native-lib): remove deprecated SetFileDescriptorLimit GraalVM flag
The -H:-SetFileDescriptorLimit option has been removed in newer GraalVM versions
(24.x and later). This flag was originally added to suppress a harmless macOS
setrlimit warning (errno 22) but is no longer recognized.

Error message:
  Error: Could not find option 'SetFileDescriptorLimit' from 'user'.

Fix: Remove the flag entirely. Modern GraalVM versions handle this internally.